// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/lookingglass.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent status
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_ONLINE      AgentStatus = 1
	AgentStatus_AGENT_STATUS_OFFLINE     AgentStatus = 2
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_ONLINE",
		2: "AGENT_STATUS_OFFLINE",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_ONLINE":      1,
		"AGENT_STATUS_OFFLINE":     2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lookingglass_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_proto_lookingglass_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{0}
}

// Task status
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
		"TASK_STATUS_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lookingglass_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_lookingglass_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{1}
}

// Task type
type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED    TaskType = 0
	TaskType_TASK_TYPE_PING           TaskType = 1
	TaskType_TASK_TYPE_MTR            TaskType = 2
	TaskType_TASK_TYPE_TRACEROUTE     TaskType = 3
	TaskType_TASK_TYPE_SYSBENCH       TaskType = 4
	TaskType_TASK_TYPE_NEXTTRACE      TaskType = 5
	TaskType_TASK_TYPE_CUSTOM_COMMAND TaskType = 6 // Custom command execution
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_PING",
		2: "TASK_TYPE_MTR",
		3: "TASK_TYPE_TRACEROUTE",
		4: "TASK_TYPE_SYSBENCH",
		5: "TASK_TYPE_NEXTTRACE",
		6: "TASK_TYPE_CUSTOM_COMMAND",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED":    0,
		"TASK_TYPE_PING":           1,
		"TASK_TYPE_MTR":            2,
		"TASK_TYPE_TRACEROUTE":     3,
		"TASK_TYPE_SYSBENCH":       4,
		"TASK_TYPE_NEXTTRACE":      5,
		"TASK_TYPE_CUSTOM_COMMAND": 6,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lookingglass_proto_enumTypes[2].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_lookingglass_proto_enumTypes[2]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{2}
}

// Authentication mode
type AuthMode int32

const (
	AuthMode_AUTH_MODE_UNSPECIFIED  AuthMode = 0
	AuthMode_AUTH_MODE_API_KEY      AuthMode = 1
	AuthMode_AUTH_MODE_IP_WHITELIST AuthMode = 2
)

// Enum value maps for AuthMode.
var (
	AuthMode_name = map[int32]string{
		0: "AUTH_MODE_UNSPECIFIED",
		1: "AUTH_MODE_API_KEY",
		2: "AUTH_MODE_IP_WHITELIST",
	}
	AuthMode_value = map[string]int32{
		"AUTH_MODE_UNSPECIFIED":  0,
		"AUTH_MODE_API_KEY":      1,
		"AUTH_MODE_IP_WHITELIST": 2,
	}
)

func (x AuthMode) Enum() *AuthMode {
	p := new(AuthMode)
	*p = x
	return p
}

func (x AuthMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lookingglass_proto_enumTypes[3].Descriptor()
}

func (AuthMode) Type() protoreflect.EnumType {
	return &file_proto_lookingglass_proto_enumTypes[3]
}

func (x AuthMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMode.Descriptor instead.
func (AuthMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{3}
}

type AgentMessage_Type int32

const (
	AgentMessage_TYPE_UNSPECIFIED   AgentMessage_Type = 0
	AgentMessage_TYPE_REGISTER      AgentMessage_Type = 1 // Agent registration
	AgentMessage_TYPE_HEARTBEAT     AgentMessage_Type = 2 // Heartbeat
	AgentMessage_TYPE_TASK_OUTPUT   AgentMessage_Type = 3 // Task execution output
	AgentMessage_TYPE_TASK_COMPLETE AgentMessage_Type = 4 // Task completion
	AgentMessage_TYPE_TASK_FAILED   AgentMessage_Type = 5 // Task failure
)

// Enum value maps for AgentMessage_Type.
var (
	AgentMessage_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_REGISTER",
		2: "TYPE_HEARTBEAT",
		3: "TYPE_TASK_OUTPUT",
		4: "TYPE_TASK_COMPLETE",
		5: "TYPE_TASK_FAILED",
	}
	AgentMessage_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":   0,
		"TYPE_REGISTER":      1,
		"TYPE_HEARTBEAT":     2,
		"TYPE_TASK_OUTPUT":   3,
		"TYPE_TASK_COMPLETE": 4,
		"TYPE_TASK_FAILED":   5,
	}
)

func (x AgentMessage_Type) Enum() *AgentMessage_Type {
	p := new(AgentMessage_Type)
	*p = x
	return p
}

func (x AgentMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lookingglass_proto_enumTypes[4].Descriptor()
}

func (AgentMessage_Type) Type() protoreflect.EnumType {
	return &file_proto_lookingglass_proto_enumTypes[4]
}

func (x AgentMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentMessage_Type.Descriptor instead.
func (AgentMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{13, 0}
}

type MasterMessage_Type int32

const (
	MasterMessage_TYPE_UNSPECIFIED        MasterMessage_Type = 0
	MasterMessage_TYPE_REGISTER_RESPONSE  MasterMessage_Type = 1 // Registration response
	MasterMessage_TYPE_HEARTBEAT_RESPONSE MasterMessage_Type = 2 // Heartbeat response
	MasterMessage_TYPE_EXECUTE_TASK       MasterMessage_Type = 3 // Execute task command
	MasterMessage_TYPE_CANCEL_TASK        MasterMessage_Type = 4 // Cancel task command
	MasterMessage_TYPE_ACK                MasterMessage_Type = 5 // Generic acknowledgment
)

// Enum value maps for MasterMessage_Type.
var (
	MasterMessage_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_REGISTER_RESPONSE",
		2: "TYPE_HEARTBEAT_RESPONSE",
		3: "TYPE_EXECUTE_TASK",
		4: "TYPE_CANCEL_TASK",
		5: "TYPE_ACK",
	}
	MasterMessage_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":        0,
		"TYPE_REGISTER_RESPONSE":  1,
		"TYPE_HEARTBEAT_RESPONSE": 2,
		"TYPE_EXECUTE_TASK":       3,
		"TYPE_CANCEL_TASK":        4,
		"TYPE_ACK":                5,
	}
)

func (x MasterMessage_Type) Enum() *MasterMessage_Type {
	p := new(MasterMessage_Type)
	*p = x
	return p
}

func (x MasterMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MasterMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lookingglass_proto_enumTypes[5].Descriptor()
}

func (MasterMessage_Type) Type() protoreflect.EnumType {
	return &file_proto_lookingglass_proto_enumTypes[5]
}

func (x MasterMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MasterMessage_Type.Descriptor instead.
func (MasterMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{14, 0}
}

type WSRequest_Action int32

const (
	WSRequest_ACTION_UNSPECIFIED WSRequest_Action = 0
	WSRequest_ACTION_EXECUTE     WSRequest_Action = 1
	WSRequest_ACTION_CANCEL      WSRequest_Action = 2
	WSRequest_ACTION_LIST_AGENTS WSRequest_Action = 3 // Request agent list
)

// Enum value maps for WSRequest_Action.
var (
	WSRequest_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_EXECUTE",
		2: "ACTION_CANCEL",
		3: "ACTION_LIST_AGENTS",
	}
	WSRequest_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_EXECUTE":     1,
		"ACTION_CANCEL":      2,
		"ACTION_LIST_AGENTS": 3,
	}
)

func (x WSRequest_Action) Enum() *WSRequest_Action {
	p := new(WSRequest_Action)
	*p = x
	return p
}

func (x WSRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WSRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lookingglass_proto_enumTypes[6].Descriptor()
}

func (WSRequest_Action) Type() protoreflect.EnumType {
	return &file_proto_lookingglass_proto_enumTypes[6]
}

func (x WSRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WSRequest_Action.Descriptor instead.
func (WSRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{20, 0}
}

type WSResponse_Type int32

const (
	WSResponse_TYPE_UNSPECIFIED         WSResponse_Type = 0
	WSResponse_TYPE_OUTPUT              WSResponse_Type = 1
	WSResponse_TYPE_ERROR               WSResponse_Type = 2
	WSResponse_TYPE_COMPLETE            WSResponse_Type = 3
	WSResponse_TYPE_TASK_STARTED        WSResponse_Type = 4
	WSResponse_TYPE_AGENT_LIST          WSResponse_Type = 5 // Agent list response
	WSResponse_TYPE_AGENT_STATUS_UPDATE WSResponse_Type = 6 // Agent status update (server push)
)

// Enum value maps for WSResponse_Type.
var (
	WSResponse_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_OUTPUT",
		2: "TYPE_ERROR",
		3: "TYPE_COMPLETE",
		4: "TYPE_TASK_STARTED",
		5: "TYPE_AGENT_LIST",
		6: "TYPE_AGENT_STATUS_UPDATE",
	}
	WSResponse_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":         0,
		"TYPE_OUTPUT":              1,
		"TYPE_ERROR":               2,
		"TYPE_COMPLETE":            3,
		"TYPE_TASK_STARTED":        4,
		"TYPE_AGENT_LIST":          5,
		"TYPE_AGENT_STATUS_UPDATE": 6,
	}
)

func (x WSResponse_Type) Enum() *WSResponse_Type {
	p := new(WSResponse_Type)
	*p = x
	return p
}

func (x WSResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WSResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lookingglass_proto_enumTypes[7].Descriptor()
}

func (WSResponse_Type) Type() protoreflect.EnumType {
	return &file_proto_lookingglass_proto_enumTypes[7]
}

func (x WSResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WSResponse_Type.Descriptor instead.
func (WSResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{21, 0}
}

// Task metadata for frontend display (used for both builtin and custom tasks)
type TaskDisplayInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskName       string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`                    // Internal task name (e.g., "ping", "curl_test")
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`           // Display name for frontend (e.g., "Ping", "HTTP Check")
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                              // Optional description
	RequiresTarget bool                   `protobuf:"varint,4,opt,name=requires_target,json=requiresTarget,proto3" json:"requires_target,omitempty"` // Whether this task requires a target parameter (default: true)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskDisplayInfo) Reset() {
	*x = TaskDisplayInfo{}
	mi := &file_proto_lookingglass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDisplayInfo) ProtoMessage() {}

func (x *TaskDisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDisplayInfo.ProtoReflect.Descriptor instead.
func (*TaskDisplayInfo) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDisplayInfo) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskDisplayInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TaskDisplayInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskDisplayInfo) GetRequiresTarget() bool {
	if x != nil {
		return x.RequiresTarget
	}
	return false
}

// Deprecated: Use TaskDisplayInfo instead
type CustomCommandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomCommandInfo) Reset() {
	*x = CustomCommandInfo{}
	mi := &file_proto_lookingglass_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomCommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomCommandInfo) ProtoMessage() {}

func (x *CustomCommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomCommandInfo.ProtoReflect.Descriptor instead.
func (*CustomCommandInfo) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{1}
}

func (x *CustomCommandInfo) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *CustomCommandInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CustomCommandInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AgentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                  // Unique identifier (e.g., "us-west-1")
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                              // Display name (e.g., "美国西部-洛杉矶")
	Location        string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`                                                                      // Geographic location
	Ipv4            string                 `protobuf:"bytes,4,opt,name=ipv4,proto3" json:"ipv4,omitempty"`                                                                              // IPv4 address
	Ipv6            string                 `protobuf:"bytes,5,opt,name=ipv6,proto3" json:"ipv6,omitempty"`                                                                              // IPv6 address (optional)
	Host            string                 `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`                                                                              // Agent gRPC address (host:port)
	MaxConcurrent   int32                  `protobuf:"varint,7,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`                                      // Maximum concurrent tasks
	SupportedTasks  []TaskType             `protobuf:"varint,8,rep,packed,name=supported_tasks,json=supportedTasks,proto3,enum=lookingglass.TaskType" json:"supported_tasks,omitempty"` // [DEPRECATED] Use task_names instead
	HideIp          bool                   `protobuf:"varint,9,opt,name=hide_ip,json=hideIp,proto3" json:"hide_ip,omitempty"`                                                           // Whether to hide IP address (mask last 2 octets)
	Provider        string                 `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`                                                                     // Service provider (e.g., "AWS", "DigitalOcean")
	Idc             string                 `protobuf:"bytes,11,opt,name=idc,proto3" json:"idc,omitempty"`                                                                               // Data center (e.g., "us-west-1a")
	Description     string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`                                                               // Additional description
	CustomCommands  []*CustomCommandInfo   `protobuf:"bytes,13,rep,name=custom_commands,json=customCommands,proto3" json:"custom_commands,omitempty"`                                   // [DEPRECATED] Use task_display_info instead
	TaskNames       []string               `protobuf:"bytes,14,rep,name=task_names,json=taskNames,proto3" json:"task_names,omitempty"`                                                  // [DEPRECATED] Use task_display_info instead
	TaskDisplayInfo []*TaskDisplayInfo     `protobuf:"bytes,15,rep,name=task_display_info,json=taskDisplayInfo,proto3" json:"task_display_info,omitempty"`                              // Task display information (name + display_name)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_proto_lookingglass_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AgentInfo) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *AgentInfo) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *AgentInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AgentInfo) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *AgentInfo) GetSupportedTasks() []TaskType {
	if x != nil {
		return x.SupportedTasks
	}
	return nil
}

func (x *AgentInfo) GetHideIp() bool {
	if x != nil {
		return x.HideIp
	}
	return false
}

func (x *AgentInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentInfo) GetIdc() string {
	if x != nil {
		return x.Idc
	}
	return ""
}

func (x *AgentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentInfo) GetCustomCommands() []*CustomCommandInfo {
	if x != nil {
		return x.CustomCommands
	}
	return nil
}

func (x *AgentInfo) GetTaskNames() []string {
	if x != nil {
		return x.TaskNames
	}
	return nil
}

func (x *AgentInfo) GetTaskDisplayInfo() []*TaskDisplayInfo {
	if x != nil {
		return x.TaskDisplayInfo
	}
	return nil
}

type AgentStatus_Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        AgentStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=lookingglass.AgentStatus" json:"status,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	CurrentTasks  int32                  `protobuf:"varint,4,opt,name=current_tasks,json=currentTasks,proto3" json:"current_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus_Message) Reset() {
	*x = AgentStatus_Message{}
	mi := &file_proto_lookingglass_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus_Message) ProtoMessage() {}

func (x *AgentStatus_Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus_Message.ProtoReflect.Descriptor instead.
func (*AgentStatus_Message) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{3}
}

func (x *AgentStatus_Message) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatus_Message) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *AgentStatus_Message) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *AgentStatus_Message) GetCurrentTasks() int32 {
	if x != nil {
		return x.CurrentTasks
	}
	return 0
}

// Network test parameters (ping, mtr, traceroute)
type NetworkTestParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Target         string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`                                                                                                           // Target IP or domain
	Count          int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                                                                                                            // Number of packets/hops
	Timeout        int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                                                        // Timeout in seconds
	Ipv6           bool                   `protobuf:"varint,4,opt,name=ipv6,proto3" json:"ipv6,omitempty"`                                                                                                              // Use IPv6
	ExtraOptions   map[string]string      `protobuf:"bytes,5,rep,name=extra_options,json=extraOptions,proto3" json:"extra_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extra command-line options
	CustomTaskName string                 `protobuf:"bytes,6,opt,name=custom_task_name,json=customTaskName,proto3" json:"custom_task_name,omitempty"`                                                                   // [DEPRECATED] Use Task.task_name instead
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkTestParams) Reset() {
	*x = NetworkTestParams{}
	mi := &file_proto_lookingglass_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTestParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTestParams) ProtoMessage() {}

func (x *NetworkTestParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTestParams.ProtoReflect.Descriptor instead.
func (*NetworkTestParams) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkTestParams) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *NetworkTestParams) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NetworkTestParams) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *NetworkTestParams) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

func (x *NetworkTestParams) GetExtraOptions() map[string]string {
	if x != nil {
		return x.ExtraOptions
	}
	return nil
}

func (x *NetworkTestParams) GetCustomTaskName() string {
	if x != nil {
		return x.CustomTaskName
	}
	return ""
}

// Benchmark parameters (sysbench, etc.)
type BenchmarkParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestType      string                 `protobuf:"bytes,1,opt,name=test_type,json=testType,proto3" json:"test_type,omitempty"`                                                         // cpu/memory/io
	Threads       int32                  `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`                                                                          // Number of threads
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`                                                                        // Test duration in seconds
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extra options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BenchmarkParams) Reset() {
	*x = BenchmarkParams{}
	mi := &file_proto_lookingglass_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkParams) ProtoMessage() {}

func (x *BenchmarkParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkParams.ProtoReflect.Descriptor instead.
func (*BenchmarkParams) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{5}
}

func (x *BenchmarkParams) GetTestType() string {
	if x != nil {
		return x.TestType
	}
	return ""
}

func (x *BenchmarkParams) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *BenchmarkParams) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BenchmarkParams) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Custom parameters for fully flexible commands
type CustomParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`             // Serialized parameters
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // Data format identifier (e.g., "json", "yaml")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomParams) Reset() {
	*x = CustomParams{}
	mi := &file_proto_lookingglass_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomParams) ProtoMessage() {}

func (x *CustomParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomParams.ProtoReflect.Descriptor instead.
func (*CustomParams) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{6}
}

func (x *CustomParams) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *CustomParams) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// Task definition
type Task struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TaskId    string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`           // Unique task identifier
	AgentId   string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`        // Target agent ID
	TaskName  string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`     // Task name (e.g., "ping", "mtr", "curl_test")
	Type      TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=lookingglass.TaskType" json:"type,omitempty"` // [DEPRECATED] Task type enum - use task_name instead
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Timeout   int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"` // Task timeout in seconds
	// Task parameters (oneof for type safety)
	//
	// Types that are valid to be assigned to Params:
	//
	//	*Task_NetworkTest
	//	*Task_Benchmark
	//	*Task_Custom
	Params        isTask_Params `protobuf_oneof:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_lookingglass_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{7}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Task) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *Task) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Task) GetParams() isTask_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Task) GetNetworkTest() *NetworkTestParams {
	if x != nil {
		if x, ok := x.Params.(*Task_NetworkTest); ok {
			return x.NetworkTest
		}
	}
	return nil
}

func (x *Task) GetBenchmark() *BenchmarkParams {
	if x != nil {
		if x, ok := x.Params.(*Task_Benchmark); ok {
			return x.Benchmark
		}
	}
	return nil
}

func (x *Task) GetCustom() *CustomParams {
	if x != nil {
		if x, ok := x.Params.(*Task_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isTask_Params interface {
	isTask_Params()
}

type Task_NetworkTest struct {
	NetworkTest *NetworkTestParams `protobuf:"bytes,10,opt,name=network_test,json=networkTest,proto3,oneof"`
}

type Task_Benchmark struct {
	Benchmark *BenchmarkParams `protobuf:"bytes,11,opt,name=benchmark,proto3,oneof"`
}

type Task_Custom struct {
	Custom *CustomParams `protobuf:"bytes,12,opt,name=custom,proto3,oneof"`
}

func (*Task_NetworkTest) isTask_Params() {}

func (*Task_Benchmark) isTask_Params() {}

func (*Task_Custom) isTask_Params() {}

// Task output (streamed from Agent to Master)
type TaskOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	OutputLine    string                 `protobuf:"bytes,2,opt,name=output_line,json=outputLine,proto3" json:"output_line,omitempty"` // Single line of output
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=lookingglass.TaskStatus" json:"status,omitempty"`   // Current task status
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message (if failed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	mi := &file_proto_lookingglass_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{8}
}

func (x *TaskOutput) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOutput) GetOutputLine() string {
	if x != nil {
		return x.OutputLine
	}
	return ""
}

func (x *TaskOutput) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskOutput) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Register request
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentInfo     *AgentInfo             `protobuf:"bytes,1,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_lookingglass_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterRequest) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

// Register response
type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatInterval int32                  `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // Heartbeat interval in seconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_lookingglass_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

// Heartbeat request
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CurrentTasks  int32                  `protobuf:"varint,2,opt,name=current_tasks,json=currentTasks,proto3" json:"current_tasks,omitempty"` // Number of currently running tasks
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_lookingglass_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentTasks() int32 {
	if x != nil {
		return x.CurrentTasks
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Heartbeat response
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_lookingglass_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Agent -> Master message
type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique request ID for async request/response
	Type      AgentMessage_Type      `protobuf:"varint,2,opt,name=type,proto3,enum=lookingglass.AgentMessage_Type" json:"type,omitempty"`
	// Message payload (oneof based on type)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_TaskOutput
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_lookingglass_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{13}
}

func (x *AgentMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentMessage) GetType() AgentMessage_Type {
	if x != nil {
		return x.Type
	}
	return AgentMessage_TYPE_UNSPECIFIED
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskOutput() *TaskOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskOutput); ok {
			return x.TaskOutput
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_TaskOutput struct {
	TaskOutput *TaskOutput `protobuf:"bytes,12,opt,name=task_output,json=taskOutput,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_TaskOutput) isAgentMessage_Payload() {}

// Master -> Agent message
type MasterMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Request ID (for response) or new request ID
	Type      MasterMessage_Type     `protobuf:"varint,2,opt,name=type,proto3,enum=lookingglass.MasterMessage_Type" json:"type,omitempty"`
	// Message payload (oneof based on type)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*MasterMessage_RegisterResponse
	//	*MasterMessage_HeartbeatResponse
	//	*MasterMessage_ExecuteTask
	//	*MasterMessage_CancelTask
	Payload       isMasterMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_proto_lookingglass_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{14}
}

func (x *MasterMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MasterMessage) GetType() MasterMessage_Type {
	if x != nil {
		return x.Type
	}
	return MasterMessage_TYPE_UNSPECIFIED
}

func (x *MasterMessage) GetPayload() isMasterMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MasterMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *MasterMessage) GetHeartbeatResponse() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_HeartbeatResponse); ok {
			return x.HeartbeatResponse
		}
	}
	return nil
}

func (x *MasterMessage) GetExecuteTask() *ExecuteTaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_ExecuteTask); ok {
			return x.ExecuteTask
		}
	}
	return nil
}

func (x *MasterMessage) GetCancelTask() *CancelTaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

type isMasterMessage_Payload interface {
	isMasterMessage_Payload()
}

type MasterMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,10,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type MasterMessage_HeartbeatResponse struct {
	HeartbeatResponse *HeartbeatResponse `protobuf:"bytes,11,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof"`
}

type MasterMessage_ExecuteTask struct {
	ExecuteTask *ExecuteTaskRequest `protobuf:"bytes,12,opt,name=execute_task,json=executeTask,proto3,oneof"`
}

type MasterMessage_CancelTask struct {
	CancelTask *CancelTaskRequest `protobuf:"bytes,13,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

func (*MasterMessage_RegisterResponse) isMasterMessage_Payload() {}

func (*MasterMessage_HeartbeatResponse) isMasterMessage_Payload() {}

func (*MasterMessage_ExecuteTask) isMasterMessage_Payload() {}

func (*MasterMessage_CancelTask) isMasterMessage_Payload() {}

// Execute task request
type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_proto_lookingglass_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Cancel task request
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_proto_lookingglass_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{16}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Cancel task response
type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_proto_lookingglass_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{17}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_lookingglass_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentTasks  int32                  `protobuf:"varint,3,opt,name=current_tasks,json=currentTasks,proto3" json:"current_tasks,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,4,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_lookingglass_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{19}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetCurrentTasks() int32 {
	if x != nil {
		return x.CurrentTasks
	}
	return 0
}

func (x *HealthCheckResponse) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

// WebSocket request message
type WSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        WSRequest_Action       `protobuf:"varint,1,opt,name=action,proto3,enum=lookingglass.WSRequest_Action" json:"action,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`                   // For ACTION_EXECUTE
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // For ACTION_CANCEL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSRequest) Reset() {
	*x = WSRequest{}
	mi := &file_proto_lookingglass_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSRequest) ProtoMessage() {}

func (x *WSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSRequest.ProtoReflect.Descriptor instead.
func (*WSRequest) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{20}
}

func (x *WSRequest) GetAction() WSRequest_Action {
	if x != nil {
		return x.Action
	}
	return WSRequest_ACTION_UNSPECIFIED
}

func (x *WSRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *WSRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// WebSocket response message
type WSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WSResponse_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=lookingglass.WSResponse_Type" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`   // Output line for TYPE_OUTPUT
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // Error message or status message
	Agents        []*AgentStatusInfo     `protobuf:"bytes,5,rep,name=agents,proto3" json:"agents,omitempty"`   // Agent list for TYPE_AGENT_LIST and TYPE_AGENT_STATUS_UPDATE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSResponse) Reset() {
	*x = WSResponse{}
	mi := &file_proto_lookingglass_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSResponse) ProtoMessage() {}

func (x *WSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSResponse.ProtoReflect.Descriptor instead.
func (*WSResponse) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{21}
}

func (x *WSResponse) GetType() WSResponse_Type {
	if x != nil {
		return x.Type
	}
	return WSResponse_TYPE_UNSPECIFIED
}

func (x *WSResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WSResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *WSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WSResponse) GetAgents() []*AgentStatusInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// Agent status info for WebSocket response
type AgentStatusInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location        string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Ipv4            string                 `protobuf:"bytes,4,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6            string                 `protobuf:"bytes,5,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Status          AgentStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=lookingglass.AgentStatus" json:"status,omitempty"`
	SupportedTasks  []TaskType             `protobuf:"varint,7,rep,packed,name=supported_tasks,json=supportedTasks,proto3,enum=lookingglass.TaskType" json:"supported_tasks,omitempty"` // [DEPRECATED] Use task_names instead
	CurrentTasks    int32                  `protobuf:"varint,8,opt,name=current_tasks,json=currentTasks,proto3" json:"current_tasks,omitempty"`
	MaxConcurrent   int32                  `protobuf:"varint,9,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Provider        string                 `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`                                        // Service provider
	Idc             string                 `protobuf:"bytes,11,opt,name=idc,proto3" json:"idc,omitempty"`                                                  // Data center
	Description     string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`                                  // Additional description
	CustomCommands  []*CustomCommandInfo   `protobuf:"bytes,13,rep,name=custom_commands,json=customCommands,proto3" json:"custom_commands,omitempty"`      // [DEPRECATED] Use task_display_info instead
	TaskNames       []string               `protobuf:"bytes,14,rep,name=task_names,json=taskNames,proto3" json:"task_names,omitempty"`                     // [DEPRECATED] Use task_display_info instead
	TaskDisplayInfo []*TaskDisplayInfo     `protobuf:"bytes,15,rep,name=task_display_info,json=taskDisplayInfo,proto3" json:"task_display_info,omitempty"` // Task display information (name + display_name)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentStatusInfo) Reset() {
	*x = AgentStatusInfo{}
	mi := &file_proto_lookingglass_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusInfo) ProtoMessage() {}

func (x *AgentStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookingglass_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusInfo.ProtoReflect.Descriptor instead.
func (*AgentStatusInfo) Descriptor() ([]byte, []int) {
	return file_proto_lookingglass_proto_rawDescGZIP(), []int{22}
}

func (x *AgentStatusInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentStatusInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentStatusInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AgentStatusInfo) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *AgentStatusInfo) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *AgentStatusInfo) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *AgentStatusInfo) GetSupportedTasks() []TaskType {
	if x != nil {
		return x.SupportedTasks
	}
	return nil
}

func (x *AgentStatusInfo) GetCurrentTasks() int32 {
	if x != nil {
		return x.CurrentTasks
	}
	return 0
}

func (x *AgentStatusInfo) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *AgentStatusInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentStatusInfo) GetIdc() string {
	if x != nil {
		return x.Idc
	}
	return ""
}

func (x *AgentStatusInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentStatusInfo) GetCustomCommands() []*CustomCommandInfo {
	if x != nil {
		return x.CustomCommands
	}
	return nil
}

func (x *AgentStatusInfo) GetTaskNames() []string {
	if x != nil {
		return x.TaskNames
	}
	return nil
}

func (x *AgentStatusInfo) GetTaskDisplayInfo() []*TaskDisplayInfo {
	if x != nil {
		return x.TaskDisplayInfo
	}
	return nil
}

var File_proto_lookingglass_proto protoreflect.FileDescriptor

const file_proto_lookingglass_proto_rawDesc = "" +
	"\n" +
	"\x18proto/lookingglass.proto\x12\flookingglass\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x0fTaskDisplayInfo\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0frequires_target\x18\x04 \x01(\bR\x0erequiresTarget\"u\n" +
	"\x11CustomCommandInfo\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8c\x04\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x12\n" +
	"\x04ipv4\x18\x04 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x05 \x01(\tR\x04ipv6\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12%\n" +
	"\x0emax_concurrent\x18\a \x01(\x05R\rmaxConcurrent\x12?\n" +
	"\x0fsupported_tasks\x18\b \x03(\x0e2\x16.lookingglass.TaskTypeR\x0esupportedTasks\x12\x17\n" +
	"\ahide_ip\x18\t \x01(\bR\x06hideIp\x12\x1a\n" +
	"\bprovider\x18\n" +
	" \x01(\tR\bprovider\x12\x10\n" +
	"\x03idc\x18\v \x01(\tR\x03idc\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12H\n" +
	"\x0fcustom_commands\x18\r \x03(\v2\x1f.lookingglass.CustomCommandInfoR\x0ecustomCommands\x12\x1d\n" +
	"\n" +
	"task_names\x18\x0e \x03(\tR\ttaskNames\x12I\n" +
	"\x11task_display_info\x18\x0f \x03(\v2\x1d.lookingglass.TaskDisplayInfoR\x0ftaskDisplayInfo\"\xcb\x01\n" +
	"\x13AgentStatus_Message\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.lookingglass.AgentStatusR\x06status\x12A\n" +
	"\x0elast_heartbeat\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12#\n" +
	"\rcurrent_tasks\x18\x04 \x01(\x05R\fcurrentTasks\"\xb2\x02\n" +
	"\x11NetworkTestParams\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\x12\x12\n" +
	"\x04ipv6\x18\x04 \x01(\bR\x04ipv6\x12V\n" +
	"\rextra_options\x18\x05 \x03(\v21.lookingglass.NetworkTestParams.ExtraOptionsEntryR\fextraOptions\x12(\n" +
	"\x10custom_task_name\x18\x06 \x01(\tR\x0ecustomTaskName\x1a?\n" +
	"\x11ExtraOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x0fBenchmarkParams\x12\x1b\n" +
	"\ttest_type\x18\x01 \x01(\tR\btestType\x12\x18\n" +
	"\athreads\x18\x02 \x01(\x05R\athreads\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12D\n" +
	"\aoptions\x18\x04 \x03(\v2*.lookingglass.BenchmarkParams.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\fCustomParams\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\x9d\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.lookingglass.TaskTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x12D\n" +
	"\fnetwork_test\x18\n" +
	" \x01(\v2\x1f.lookingglass.NetworkTestParamsH\x00R\vnetworkTest\x12=\n" +
	"\tbenchmark\x18\v \x01(\v2\x1d.lookingglass.BenchmarkParamsH\x00R\tbenchmark\x124\n" +
	"\x06custom\x18\f \x01(\v2\x1a.lookingglass.CustomParamsH\x00R\x06customB\b\n" +
	"\x06params\"\xd7\x01\n" +
	"\n" +
	"TaskOutput\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\voutput_line\x18\x02 \x01(\tR\n" +
	"outputLine\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.lookingglass.TaskStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"I\n" +
	"\x0fRegisterRequest\x126\n" +
	"\n" +
	"agent_info\x18\x01 \x01(\v2\x17.lookingglass.AgentInfoR\tagentInfo\"u\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\x05R\x11heartbeatInterval\"\x8c\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rcurrent_tasks\x18\x02 \x01(\x05R\fcurrentTasks\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb1\x03\n" +
	"\fAgentMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.lookingglass.AgentMessage.TypeR\x04type\x12;\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x1d.lookingglass.RegisterRequestH\x00R\bregister\x12>\n" +
	"\theartbeat\x18\v \x01(\v2\x1e.lookingglass.HeartbeatRequestH\x00R\theartbeat\x12;\n" +
	"\vtask_output\x18\f \x01(\v2\x18.lookingglass.TaskOutputH\x00R\n" +
	"taskOutput\"\x87\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTYPE_REGISTER\x10\x01\x12\x12\n" +
	"\x0eTYPE_HEARTBEAT\x10\x02\x12\x14\n" +
	"\x10TYPE_TASK_OUTPUT\x10\x03\x12\x16\n" +
	"\x12TYPE_TASK_COMPLETE\x10\x04\x12\x14\n" +
	"\x10TYPE_TASK_FAILED\x10\x05B\t\n" +
	"\apayload\"\xae\x04\n" +
	"\rMasterMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .lookingglass.MasterMessage.TypeR\x04type\x12M\n" +
	"\x11register_response\x18\n" +
	" \x01(\v2\x1e.lookingglass.RegisterResponseH\x00R\x10registerResponse\x12P\n" +
	"\x12heartbeat_response\x18\v \x01(\v2\x1f.lookingglass.HeartbeatResponseH\x00R\x11heartbeatResponse\x12E\n" +
	"\fexecute_task\x18\f \x01(\v2 .lookingglass.ExecuteTaskRequestH\x00R\vexecuteTask\x12B\n" +
	"\vcancel_task\x18\r \x01(\v2\x1f.lookingglass.CancelTaskRequestH\x00R\n" +
	"cancelTask\"\x90\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TYPE_REGISTER_RESPONSE\x10\x01\x12\x1b\n" +
	"\x17TYPE_HEARTBEAT_RESPONSE\x10\x02\x12\x15\n" +
	"\x11TYPE_EXECUTE_TASK\x10\x03\x12\x14\n" +
	"\x10TYPE_CANCEL_TASK\x10\x04\x12\f\n" +
	"\bTYPE_ACK\x10\x05B\t\n" +
	"\apayload\"<\n" +
	"\x12ExecuteTaskRequest\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.lookingglass.TaskR\x04task\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x12HealthCheckRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x95\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcurrent_tasks\x18\x03 \x01(\x05R\fcurrentTasks\x12%\n" +
	"\x0emax_concurrent\x18\x04 \x01(\x05R\rmaxConcurrent\"\xe5\x01\n" +
	"\tWSRequest\x126\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1e.lookingglass.WSRequest.ActionR\x06action\x12&\n" +
	"\x04task\x18\x02 \x01(\v2\x12.lookingglass.TaskR\x04task\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"_\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eACTION_EXECUTE\x10\x01\x12\x11\n" +
	"\rACTION_CANCEL\x10\x02\x12\x16\n" +
	"\x12ACTION_LIST_AGENTS\x10\x03\"\xde\x02\n" +
	"\n" +
	"WSResponse\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.lookingglass.WSResponse.TypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x125\n" +
	"\x06agents\x18\x05 \x03(\v2\x1d.lookingglass.AgentStatusInfoR\x06agents\"\x9a\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_OUTPUT\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_ERROR\x10\x02\x12\x11\n" +
	"\rTYPE_COMPLETE\x10\x03\x12\x15\n" +
	"\x11TYPE_TASK_STARTED\x10\x04\x12\x13\n" +
	"\x0fTYPE_AGENT_LIST\x10\x05\x12\x1c\n" +
	"\x18TYPE_AGENT_STATUS_UPDATE\x10\x06\"\xbd\x04\n" +
	"\x0fAgentStatusInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x12\n" +
	"\x04ipv4\x18\x04 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x05 \x01(\tR\x04ipv6\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.lookingglass.AgentStatusR\x06status\x12?\n" +
	"\x0fsupported_tasks\x18\a \x03(\x0e2\x16.lookingglass.TaskTypeR\x0esupportedTasks\x12#\n" +
	"\rcurrent_tasks\x18\b \x01(\x05R\fcurrentTasks\x12%\n" +
	"\x0emax_concurrent\x18\t \x01(\x05R\rmaxConcurrent\x12\x1a\n" +
	"\bprovider\x18\n" +
	" \x01(\tR\bprovider\x12\x10\n" +
	"\x03idc\x18\v \x01(\tR\x03idc\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12H\n" +
	"\x0fcustom_commands\x18\r \x03(\v2\x1f.lookingglass.CustomCommandInfoR\x0ecustomCommands\x12\x1d\n" +
	"\n" +
	"task_names\x18\x0e \x03(\tR\ttaskNames\x12I\n" +
	"\x11task_display_info\x18\x0f \x03(\v2\x1d.lookingglass.TaskDisplayInfoR\x0ftaskDisplayInfo*^\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AGENT_STATUS_ONLINE\x10\x01\x12\x18\n" +
	"\x14AGENT_STATUS_OFFLINE\x10\x02*\xa9\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x05*\xb5\x01\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTASK_TYPE_PING\x10\x01\x12\x11\n" +
	"\rTASK_TYPE_MTR\x10\x02\x12\x18\n" +
	"\x14TASK_TYPE_TRACEROUTE\x10\x03\x12\x16\n" +
	"\x12TASK_TYPE_SYSBENCH\x10\x04\x12\x17\n" +
	"\x13TASK_TYPE_NEXTTRACE\x10\x05\x12\x1c\n" +
	"\x18TASK_TYPE_CUSTOM_COMMAND\x10\x06*X\n" +
	"\bAuthMode\x12\x19\n" +
	"\x15AUTH_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AUTH_MODE_API_KEY\x10\x01\x12\x1a\n" +
	"\x16AUTH_MODE_IP_WHITELIST\x10\x022\xf4\x01\n" +
	"\rMasterService\x12I\n" +
	"\bRegister\x12\x1d.lookingglass.RegisterRequest\x1a\x1e.lookingglass.RegisterResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.lookingglass.HeartbeatRequest\x1a\x1f.lookingglass.HeartbeatResponse\x12J\n" +
	"\vAgentStream\x12\x1a.lookingglass.AgentMessage\x1a\x1b.lookingglass.MasterMessage(\x010\x012\x80\x02\n" +
	"\fAgentService\x12K\n" +
	"\vExecuteTask\x12 .lookingglass.ExecuteTaskRequest\x1a\x18.lookingglass.TaskOutput0\x01\x12O\n" +
	"\n" +
	"CancelTask\x12\x1f.lookingglass.CancelTaskRequest\x1a .lookingglass.CancelTaskResponse\x12R\n" +
	"\vHealthCheck\x12 .lookingglass.HealthCheckRequest\x1a!.lookingglass.HealthCheckResponseB$Z\"github.com/lureiny/lookingglass/pbb\x06proto3"

var (
	file_proto_lookingglass_proto_rawDescOnce sync.Once
	file_proto_lookingglass_proto_rawDescData []byte
)

func file_proto_lookingglass_proto_rawDescGZIP() []byte {
	file_proto_lookingglass_proto_rawDescOnce.Do(func() {
		file_proto_lookingglass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lookingglass_proto_rawDesc), len(file_proto_lookingglass_proto_rawDesc)))
	})
	return file_proto_lookingglass_proto_rawDescData
}

var file_proto_lookingglass_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_proto_lookingglass_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_lookingglass_proto_goTypes = []any{
	(AgentStatus)(0),              // 0: lookingglass.AgentStatus
	(TaskStatus)(0),               // 1: lookingglass.TaskStatus
	(TaskType)(0),                 // 2: lookingglass.TaskType
	(AuthMode)(0),                 // 3: lookingglass.AuthMode
	(AgentMessage_Type)(0),        // 4: lookingglass.AgentMessage.Type
	(MasterMessage_Type)(0),       // 5: lookingglass.MasterMessage.Type
	(WSRequest_Action)(0),         // 6: lookingglass.WSRequest.Action
	(WSResponse_Type)(0),          // 7: lookingglass.WSResponse.Type
	(*TaskDisplayInfo)(nil),       // 8: lookingglass.TaskDisplayInfo
	(*CustomCommandInfo)(nil),     // 9: lookingglass.CustomCommandInfo
	(*AgentInfo)(nil),             // 10: lookingglass.AgentInfo
	(*AgentStatus_Message)(nil),   // 11: lookingglass.AgentStatus_Message
	(*NetworkTestParams)(nil),     // 12: lookingglass.NetworkTestParams
	(*BenchmarkParams)(nil),       // 13: lookingglass.BenchmarkParams
	(*CustomParams)(nil),          // 14: lookingglass.CustomParams
	(*Task)(nil),                  // 15: lookingglass.Task
	(*TaskOutput)(nil),            // 16: lookingglass.TaskOutput
	(*RegisterRequest)(nil),       // 17: lookingglass.RegisterRequest
	(*RegisterResponse)(nil),      // 18: lookingglass.RegisterResponse
	(*HeartbeatRequest)(nil),      // 19: lookingglass.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 20: lookingglass.HeartbeatResponse
	(*AgentMessage)(nil),          // 21: lookingglass.AgentMessage
	(*MasterMessage)(nil),         // 22: lookingglass.MasterMessage
	(*ExecuteTaskRequest)(nil),    // 23: lookingglass.ExecuteTaskRequest
	(*CancelTaskRequest)(nil),     // 24: lookingglass.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 25: lookingglass.CancelTaskResponse
	(*HealthCheckRequest)(nil),    // 26: lookingglass.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 27: lookingglass.HealthCheckResponse
	(*WSRequest)(nil),             // 28: lookingglass.WSRequest
	(*WSResponse)(nil),            // 29: lookingglass.WSResponse
	(*AgentStatusInfo)(nil),       // 30: lookingglass.AgentStatusInfo
	nil,                           // 31: lookingglass.NetworkTestParams.ExtraOptionsEntry
	nil,                           // 32: lookingglass.BenchmarkParams.OptionsEntry
	(*timestamppb.Timestamp)(nil), // 33: google.protobuf.Timestamp
}
var file_proto_lookingglass_proto_depIdxs = []int32{
	2,  // 0: lookingglass.AgentInfo.supported_tasks:type_name -> lookingglass.TaskType
	9,  // 1: lookingglass.AgentInfo.custom_commands:type_name -> lookingglass.CustomCommandInfo
	8,  // 2: lookingglass.AgentInfo.task_display_info:type_name -> lookingglass.TaskDisplayInfo
	0,  // 3: lookingglass.AgentStatus_Message.status:type_name -> lookingglass.AgentStatus
	33, // 4: lookingglass.AgentStatus_Message.last_heartbeat:type_name -> google.protobuf.Timestamp
	31, // 5: lookingglass.NetworkTestParams.extra_options:type_name -> lookingglass.NetworkTestParams.ExtraOptionsEntry
	32, // 6: lookingglass.BenchmarkParams.options:type_name -> lookingglass.BenchmarkParams.OptionsEntry
	2,  // 7: lookingglass.Task.type:type_name -> lookingglass.TaskType
	33, // 8: lookingglass.Task.created_at:type_name -> google.protobuf.Timestamp
	12, // 9: lookingglass.Task.network_test:type_name -> lookingglass.NetworkTestParams
	13, // 10: lookingglass.Task.benchmark:type_name -> lookingglass.BenchmarkParams
	14, // 11: lookingglass.Task.custom:type_name -> lookingglass.CustomParams
	33, // 12: lookingglass.TaskOutput.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 13: lookingglass.TaskOutput.status:type_name -> lookingglass.TaskStatus
	10, // 14: lookingglass.RegisterRequest.agent_info:type_name -> lookingglass.AgentInfo
	33, // 15: lookingglass.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 16: lookingglass.AgentMessage.type:type_name -> lookingglass.AgentMessage.Type
	17, // 17: lookingglass.AgentMessage.register:type_name -> lookingglass.RegisterRequest
	19, // 18: lookingglass.AgentMessage.heartbeat:type_name -> lookingglass.HeartbeatRequest
	16, // 19: lookingglass.AgentMessage.task_output:type_name -> lookingglass.TaskOutput
	5,  // 20: lookingglass.MasterMessage.type:type_name -> lookingglass.MasterMessage.Type
	18, // 21: lookingglass.MasterMessage.register_response:type_name -> lookingglass.RegisterResponse
	20, // 22: lookingglass.MasterMessage.heartbeat_response:type_name -> lookingglass.HeartbeatResponse
	23, // 23: lookingglass.MasterMessage.execute_task:type_name -> lookingglass.ExecuteTaskRequest
	24, // 24: lookingglass.MasterMessage.cancel_task:type_name -> lookingglass.CancelTaskRequest
	15, // 25: lookingglass.ExecuteTaskRequest.task:type_name -> lookingglass.Task
	33, // 26: lookingglass.HealthCheckRequest.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 27: lookingglass.WSRequest.action:type_name -> lookingglass.WSRequest.Action
	15, // 28: lookingglass.WSRequest.task:type_name -> lookingglass.Task
	7,  // 29: lookingglass.WSResponse.type:type_name -> lookingglass.WSResponse.Type
	30, // 30: lookingglass.WSResponse.agents:type_name -> lookingglass.AgentStatusInfo
	0,  // 31: lookingglass.AgentStatusInfo.status:type_name -> lookingglass.AgentStatus
	2,  // 32: lookingglass.AgentStatusInfo.supported_tasks:type_name -> lookingglass.TaskType
	9,  // 33: lookingglass.AgentStatusInfo.custom_commands:type_name -> lookingglass.CustomCommandInfo
	8,  // 34: lookingglass.AgentStatusInfo.task_display_info:type_name -> lookingglass.TaskDisplayInfo
	17, // 35: lookingglass.MasterService.Register:input_type -> lookingglass.RegisterRequest
	19, // 36: lookingglass.MasterService.Heartbeat:input_type -> lookingglass.HeartbeatRequest
	21, // 37: lookingglass.MasterService.AgentStream:input_type -> lookingglass.AgentMessage
	23, // 38: lookingglass.AgentService.ExecuteTask:input_type -> lookingglass.ExecuteTaskRequest
	24, // 39: lookingglass.AgentService.CancelTask:input_type -> lookingglass.CancelTaskRequest
	26, // 40: lookingglass.AgentService.HealthCheck:input_type -> lookingglass.HealthCheckRequest
	18, // 41: lookingglass.MasterService.Register:output_type -> lookingglass.RegisterResponse
	20, // 42: lookingglass.MasterService.Heartbeat:output_type -> lookingglass.HeartbeatResponse
	22, // 43: lookingglass.MasterService.AgentStream:output_type -> lookingglass.MasterMessage
	16, // 44: lookingglass.AgentService.ExecuteTask:output_type -> lookingglass.TaskOutput
	25, // 45: lookingglass.AgentService.CancelTask:output_type -> lookingglass.CancelTaskResponse
	27, // 46: lookingglass.AgentService.HealthCheck:output_type -> lookingglass.HealthCheckResponse
	41, // [41:47] is the sub-list for method output_type
	35, // [35:41] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_proto_lookingglass_proto_init() }
func file_proto_lookingglass_proto_init() {
	if File_proto_lookingglass_proto != nil {
		return
	}
	file_proto_lookingglass_proto_msgTypes[7].OneofWrappers = []any{
		(*Task_NetworkTest)(nil),
		(*Task_Benchmark)(nil),
		(*Task_Custom)(nil),
	}
	file_proto_lookingglass_proto_msgTypes[13].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_TaskOutput)(nil),
	}
	file_proto_lookingglass_proto_msgTypes[14].OneofWrappers = []any{
		(*MasterMessage_RegisterResponse)(nil),
		(*MasterMessage_HeartbeatResponse)(nil),
		(*MasterMessage_ExecuteTask)(nil),
		(*MasterMessage_CancelTask)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lookingglass_proto_rawDesc), len(file_proto_lookingglass_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_lookingglass_proto_goTypes,
		DependencyIndexes: file_proto_lookingglass_proto_depIdxs,
		EnumInfos:         file_proto_lookingglass_proto_enumTypes,
		MessageInfos:      file_proto_lookingglass_proto_msgTypes,
	}.Build()
	File_proto_lookingglass_proto = out.File
	file_proto_lookingglass_proto_goTypes = nil
	file_proto_lookingglass_proto_depIdxs = nil
}
